### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by rich-frost** [Indicia-Team/drupal-7-module-iform#11]
Hi guys,

Just gone through installing this module and also downloaded the HEAD of client_helpers; appears that `static $geoplanet_api_key='';` has been removed from _helper_config.php fairly recently which broke my install. Diff here: https://github.com/Indicia-Team/client_helpers/commit/357a678d0b90c6ad8f57bb7861ebbeeb4298c02b#diff-db5b20cac2ad4303d673d6a9812f1d91
Thanks

**Comment by JimBacon** [comment]
Hi 
Was this an upgrade to an existing installation or a new install with a clean database?
The geoplanet service ceased to exist which is why it was removed.
Do you have more details of what broke?
Thanks.

**Comment by rich-frost** [comment]
I created a completely new Drupal 7 install and added the iForm module and client_helpers. I fixed the error I was getting by adding `static $geoplanet_api_key='';` to the _helper_config.php file as I was getting an error on line 1197 of iform.module:

```helper_config::$geoplanet_api_key = variable_get('indicia_geoplanet_api_key', helper_config::$geoplanet_api_key);```

Grepping the iForm codebase there seem a few other references to indicia_geoplanet_api_key & geoplanet_api_key so I guess the correct fix would be to remove the references in this repo.

**Comment by JimBacon** [comment]
Ah, natch. All of us updating existing systems will still have it in our helper_config.php files which are outside version control, hence we haven't noticed.
