### ISSUE TITLE
Managing Groups

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/drupal-7-module-iform#9]
I am currently making use of the groups iforms. Are these still being maintained within the module or have they been superseded by generalised/dynamic reporting forms?

If they are being maintained. I currently see no way to delete a group once created. Am i missing the required iform?

**Comment by JimBacon** [comment]
Hi
iRecord uses groups and there has been quite a lot of work done fairly recently to support organisations with many sites offering activities. 
I don't see a way to delete a group either but there may be a good reason for this. If records have been submitted through a group then to delete that group might affect the integrity of the records.
Have to say I am not very familiar with them though.
